name: werewolf_cars
description: "Werewolf Cars to buy and sell cars"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  collection: ^1.17.2
  country_picker: ^2.0.26
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.1
  easy_stepper: ^0.8.3
  equatable: ^2.0.3
  expandable: ^5.0.1
  faker: ^2.1.0
  fancy_shimmer_image: ^2.0.3
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.1.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.8
  fluttertoast: ^8.2.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  geocoding_resolver: ^0.0.3+2
  geolocator: ^11.0.0
  get_it: ^7.3.0
  go_router: ^7.0.0
  google_fonts: 4.0.4
  google_maps_flutter: ^2.5.3
  group_button: ^5.3.3
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.2+1
  lottie: 2.7.0
  mobile_scanner: 2.1.0
  path_provider: ^2.1.4
  permission_handler: 11.0.0
  phone_numbers_parser: ^8.3.0
  photo_view: ^0.15.0
  pinput: ^3.0.1
  reactive_forms: ^16.1.1
  readmore: ^3.0.0
  responsive_grid_list: ^1.4.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.1.0
  simple_shadow: ^0.3.1
  smooth_page_indicator: ^1.1.0
  stream_transform: ^2.1.0
  super_tooltip: ^2.0.7
  text_scroll: ^0.2.0
  tuple: ^2.0.2
  url_launcher: ^6.2.6
  uuid: ^4.5.0
dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appIcon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/svg/
    - assets/svg/makers/
    - assets/images/
