import 'package:flutter/material.dart';
import 'package:werewolf_cars/generated/assets.dart';

const Size designSize = Size(375, 812);

const kPerPage = 20;
const List<String> makersLogos = [
  Assets.makersAlfaromeo,
  Assets.makersAstonMartin,
  Assets.makersAudi,
  Assets.makersBentley,
  Assets.makersBmw,
  Assets.makersBugatti,
  Assets.makersCadillac,
  Assets.makersChevrolet,
  Assets.makersCitroen,
  Assets.makersCupra,
  Assets.makersDacia,
  Assets.makersDaewoo,
  Assets.makersFerrari,
  Assets.makersFiat,
  Assets.makersFord,
  Assets.makersHonda,
  Assets.makersHyundai,
  Assets.makersInfiniti,
  Assets.makersIsuzu,
  Assets.makersIveco,
  Assets.makersJeep,
  Assets.makersKia,
  Assets.makersKoenigsegg,
  Assets.makersLada,
  Assets.makersLamborghini,
  Assets.makersLandrover,
  Assets.makersLexus,
  Assets.makersMan,
  Assets.makersMaserati,
  Assets.makersMazda,
  Assets.makersMcLaren,
  Assets.makersMercedes,
  Assets.makersMg,
  Assets.makersMini,
  Assets.makersMitsubishi,
  Assets.makersNissan,
  Assets.makersOpel,
  Assets.makersPeugeot,
  Assets.makersPontiac,
  Assets.makersPorsche,
  Assets.makersRollsRoyce,
  Assets.makersSeat,
  Assets.makersSkoda,
  Assets.makersSmart,
  Assets.makersSubaru,
  Assets.makersSuzuki,
  Assets.makersTesla,
  Assets.makersTogg,
  Assets.makersToyota,
  Assets.makersVolkswagen,
  Assets.makersVolvo,
];
