import 'package:werewolf_cars/generated/assets.dart';

enum CarMaker {
  bmw('BMW', Assets.makersBmw),
  mercedes('Mercedes', Assets.makersMercedes),
  audi('Audi', Assets.makersAudi),
  volkswagen('Volkswagen', Assets.makersVolkswagen),
  jeep('Jeep', Assets.makersJeep),
  toyota('Toyota', Assets.makersToyota),
  kia('Kia', Assets.makersKia),
  ford('Ford', Assets.makersFord),
  hyundai('Hyundai', Assets.makersHyundai),
  honda('Honda', Assets.makersHonda),
  porsche('Porsche', Assets.makersPorsche),
  rollsRoyce('Rolls-Royce', Assets.makersRollsRoyce),
  tesla('Tesla', Assets.makersTesla),
  bentley('Bentley', Assets.makersBentley),
  ferrari('Ferrari', Assets.makersFerrari),
  lamborghini('Lamborghini', Assets.makersLamborghini),
  nissan('Nissan', Assets.makersNissan),
  landrover('Land Rover', Assets.makersLandrover),
  lexus('Lexus', Assets.makersLexus),
  bugatti('Bugatti', Assets.makersBugatti),
  infiniti('Infiniti', Assets.makersInfiniti),
  dacia('Dacia', Assets.makersDacia),
  skoda('Skoda', Assets.makersSkoda),
  subaru('Subaru', Assets.makersSubaru),
  mitsubishi('Mitsubishi', Assets.makersMitsubishi),
  maserati('Maserati', Assets.makersMaserati),
  mazda('Mazda', Assets.makersMazda),
  alfaromeo('Alfa Romeo', Assets.makersAlfaromeo),
  astonMartin('Aston Martin', Assets.makersAstonMartin),
  cadillac('Cadillac', Assets.makersCadillac),
  chevrolet('Chevrolet', Assets.makersChevrolet),
  citroen('Citroen', Assets.makersCitroen),
  cupra('Cupra', Assets.makersCupra),
  daewoo('Daewoo', Assets.makersDaewoo),
  fiat('Fiat', Assets.makersFiat),
  isuzu('Isuzu', Assets.makersIsuzu),
  iveco('Iveco', Assets.makersIveco),
  koenigsegg('Koenigsegg', Assets.makersKoenigsegg),
  lada('Lada', Assets.makersLada),
  man('MAN', Assets.makersMan),
  mclaren('McLaren', Assets.makersMcLaren),
  mg('MG', Assets.makersMg),
  mini('Mini', Assets.makersMini),
  opel('Opel', Assets.makersOpel),
  peugeot('Peugeot', Assets.makersPeugeot),
  pontiac('Pontiac', Assets.makersPontiac),
  seat('Seat', Assets.makersSeat),
  smart('Smart', Assets.makersSmart),
  suzuki('Suzuki', Assets.makersSuzuki),
  togg('Togg', Assets.makersTogg),
  volvo('Volvo', Assets.makersVolvo);

  final String name;
  final String logoAsset;

  const CarMaker(this.name, this.logoAsset);
}
