enum ExteriorFeature {
  alloyWheels,
  fogLights,
  sunroof,
  roofRails,
  towPackage,
  powerLiftgate,
  ledHeadlights,
  runningBoards,
  rearSpoiler,
  tintedWindows,
  heatedSideMirrors,
  rainSensingWipers,
  panoramicSunroof,
  roofRack,
  dualExhaust,
}
